# Generated by Django 4.2.10 on 2024-03-06 07:24

from django.db import migrations, models
import django.db.models.deletion
import e_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('p_choices', models.CharField(choices=[('Product1', 'Product1'), ('Product2', 'Product2'), ('Product3', 'Product3'), ('Product4', 'Product4'), ('Product5', 'Product5')], default='Product1', max_length=50)),
                ('p_quantity', models.CharField(max_length=100)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_images', models.ImageField(upload_to='product_images/')),
                ('p_images_1', models.ImageField(upload_to='product_images_1/')),
                ('p_images_2', models.ImageField(upload_to='product_images_2/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='cartitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_quantity', models.PositiveIntegerField(default=0, verbose_name=e_app.models.product)),
                ('cart_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=e_app.models.product)),
                ('cart_images', models.ImageField(upload_to='cart_images/', verbose_name=e_app.models.product)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_app.product')),
            ],
            options={
                'db_table': 'cartitems',
            },
        ),
    ]
