# Generated by Django 4.2.10 on 2024-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_choices', models.CharField(choices=[('Product1', 'Product1'), ('Product2', 'Product2'), ('Product3', 'Product3'), ('Product4', 'Product4'), ('Product5', 'Product5')], default='ASSOCIATE', max_length=50)),
                ('p_quantity', models.CharField(max_length=100)),
                ('p_images', models.ImageField(upload_to='product_images/')),
                ('p_images_1', models.ImageField(upload_to='product_images_1/')),
                ('p_images_2', models.ImageField(upload_to='product_images_2/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
